- name: Install packages
  hosts: local
  connection: local
  tasks:
  - name: print names
    ansible.builtin.packages:
      name: "{{ item }}" # item is reserved
      state: latest
    loop:
    - nginx
    - mysql
    - zip